Shop0.1/Models/CartIndexViewModel.cs
using DAL.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Shop0._1.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

Shop0.1/Models/Range.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Shop0._1.Models
{
    public interface IRange
    {
        IEnumerable<int> GetRange(int a, int b);
    }
    public class Range: IRange
    {
        public IEnumerable<int> GetRange(int a, int b)
        {
            for (int i = a; i <= b; i++)
                yield  return i;
        }
    }
}

Shop0.1/Controllers/AdminController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Shop0._1.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        private IGoodRepository repository;
        public int PageSize = 8;
        public AdminController(IGoodRepository repo)
        {
            this.repository = repo;
        }
        public ViewResult Index(int id = 1)
        {
            Session["LastPage"] = id;
            int countofpages = (int)Math.Ceiling((double)(repository.GetAll().ToList().Count) / PageSize);
            ViewBag.Goods = repository.GetAll()
                                      .OrderBy(p => p.GoodId)
                                      .Skip((id - 1) * PageSize)
                                      .Take(PageSize);
            ViewBag.CountOfPages = countofpages;
            return View();
        }
        public ActionResult NewGood(int id = 0)
        {
            return View(repository.Get(id));
        }
        public ActionResult Edit(int id = 0)
        {
            return View(repository.Get(id));
        }
        [HttpPost]
        public ActionResult NewGood(Good newGood)
        {
            repository.CreateOrUpdate(newGood);
            repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            repository.Remove(repository.Get(id));
            repository.SaveChanges();

            int redirectPage = (int)Session["LastPage"];

            return RedirectToAction("Index", new { id = redirectPage });
        }
    }
}

Shop0.1/Controllers/CartController.cs
using DAL;
using DAL.Abstract;
using DAL.Entities;
using Shop0._1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop0._1.Controllers
{
    public class CartController : Controller
    {
        private IGoodRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IGoodRepository repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }
        public ViewResult Index(Cart cart ,string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public RedirectToRouteResult AddToCart(Cart cart, int goodId, string returnUrl)
        {

            Good good = repository.GetAll()
                                  .FirstOrDefault(p => p.GoodId == goodId);
            if (good != null)
            {
                cart.AddItem(good, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart, int? goodId, string returnUrl)
        {
            Good good = repository.GetAll()
                                  .FirstOrDefault(p => p.GoodId == goodId);
            if (good != null)
            {
                cart.RemoveLine(good);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            else
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            return View(shippingDetails);
            
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
    }
}






#region
//public ViewResult Index(string returnUrl)
//{
//    return View(new CartIndexViewModel
//    {
//        Cart = GetCart(),
//        ReturnUrl = returnUrl
//    });
//}

////first try of method AddToCart
////public ViewResult AddToCart(int? goodId, string returnUrl)
////{
////    Good good = repository.GetAll()
////                             .FirstOrDefault(p => p.GoodId == goodId);
////    Cart cl = GetCart();
////    if (good != null)
////    {
////        cl.AddItem(good, 1);
////    }
////    return View("Index", cl.Lines.First());
////}
//public RedirectToRouteResult AddToCart(int goodId, string returnUrl)
//{

//    Good good = repository.GetAll()
//                          .FirstOrDefault(p => p.GoodId == goodId);
//    if (good != null)
//    {
//        GetCart().AddItem(good, 1);
//    }
//    return RedirectToAction("Index", new { returnUrl });
//}
//public RedirectToRouteResult RemoveFromCart(int? goodId, string returnUrl)
//{
//    Good good = repository.GetAll()
//                          .FirstOrDefault(p => p.GoodId == goodId);
//    if (good != null)
//    {
//        GetCart().RemoveLine(good);
//    }
//    return RedirectToAction("Index", new { returnUrl });
//}
//private Cart GetCart()
//{
//    Cart cart = (Cart)Session["Cart"];
//    if (cart == null)
//    {
//        cart = new Cart();
//        Session["Cart"] = cart;
//    }
//    return cart;
//}
//    }
#endregion

Shop0.1/Controllers/GoodController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop0._1.Controllers
{
    public class GoodController : Controller
    {
        private IGoodRepository repository;
        public int PageSize = 6;
        public GoodController(IGoodRepository goodRepository)
        {
            this.repository = goodRepository;
        }
        public ViewResult AllGood(int id = 1)
        {
            int countofpages = (int)Math.Ceiling((double)(repository.GetAll().ToList().Count) / PageSize);
            ViewBag.Goods = repository.GetAll()
                                      .OrderBy(p=> p.GoodId)
                                      .Skip((id-1)* PageSize)
                                      .Take(PageSize);
            ViewBag.CountOfPages = countofpages;
            return View();
        }
        public ActionResult Cameras()
        {
            ViewBag.Goods = repository.GetAll().Where(p => p.CategoryId == 1).ToList();
            return View();
        }
        public ActionResult Lenses()
        {
            ViewBag.Goods = repository.GetAll().Where(p => p.CategoryId == 2).ToList();
            return View();
        }
        public ActionResult Camcoders()
        {
            ViewBag.Goods = repository.GetAll().Where(p => p.CategoryId == 3).ToList();
            return View();
        }
    }
}

Shop0.1/Views/Admin/Edit.cshtml
@model DAL.Good
@{
    ViewBag.Title = "Admin: Edit";
}

<div class="container">
    <div class="row justify-content-center" style="margin-top:50px;margin-bottom:50px;">
        <h2>Admin: Edit</h2>
    </div>
    @using (Html.BeginForm("NewGood", "Admin", FormMethod.Post))
    {
        <div class="row">
            <div class="col-5 border-right">
                <div class="display-1 ">
                    <img width="400"
                         src="@Url.Content("~/" + @Model.ImageUrl + ".jpg")"
                         alt="Add a photo" />
                </div>
            </div>
            <div class="col-7">
                @Html.HiddenFor(x => x.GoodId)
                <div class=" form-group row">
                    <label for="colFormLabel" class="col-sm-4 col-form-label"> Good Name :</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(m => m.GoodName)
                    </div>
                </div>
                <div class=" form-group row">
                    <label for="colFormLabel" class="col-sm-4 col-form-label"> Image Url :</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(m => m.ImageUrl)
                    </div>
                </div>
                <div class=" form-group row">
                    <label for="colFormLabel" class="col-sm-4 col-form-label"> Short Description :</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(m => m.ShortDescription)
                    </div>
                </div>
                <div class=" form-group row">
                    <label for="colFormLabel" class="col-sm-4 col-form-label"> CategoryId :</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(m => m.CategoryId)
                    </div>
                </div>
                <div class=" form-group row">
                    <label for="colFormLabel" class="col-sm-4 col-form-label"> Price :</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(m => m.Price)
                    </div>
                </div>
                <div class=" form-group row">
                    <label for="colFormLabel" class="col-sm-4 col-form-label"> Good Count :</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(m => m.GoodCount)
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    <a href="@Url.Action("Index", "Admin")" class="text-info link mr-3 p-2">Cancel and return to List</a>
                    <button type="submit" class="btn btn-outline-success">Save</button>
                </div>
            </div>
        </div>
    }
</div>

Shop0.1/Views/Admin/Index.cshtml
@model DAL.Good
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row justify-content-center" style="margin-top:50px;margin-bottom:50px;">
        <h2>Admin: All Goods</h2>
    </div>
    <div class="row">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.GoodName)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.ImageUrl)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.ShortDescription)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.Category)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.Price)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.GoodCount)</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var good in ViewBag.Goods)
                {

                    <tr>
                        <td>
                            @good.GoodId
                        </td>
                        <td>@good.GoodName</td>
                        <td>@good.ImageUrl</td>
                        <td>@good.ShortDescription</td>
                        <td>@good.CategoryId</td>
                        <td>@good.Price</td>
                        <td>@good.GoodCount</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = good.GoodId }, new { @class = "btn btn-warning btn-xs" })
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", new { id = good.GoodId }, new { @class = "btn btn-danger btn-xs" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="rov">
        @RenderPage("~/Views/Admin/Pagination.cshtml")
    </div>
    <div class="row">
        @Html.ActionLink("New good", "NewGood", null, new { @class = "btn btn-success" })
    </div>
</div>

Shop0.1/Views/Admin/NewGood.cshtml
@model DAL.Good
@{
    ViewBag.Title = "NewGood";
}

<div class="container">
    <div class="row justify-content-center" style="margin-top:50px;margin-bottom:50px;">
        <h2>Admin: New Good</h2>
    </div>
    @using (Html.BeginForm("NewGood", "Admin", FormMethod.Post))
    {
        <div class="row">
            <div class="col-7">
                @Html.HiddenFor(x => x.GoodId)
                <div class=" form-group row">
                    <label for="colFormLabel" class="col-sm-4 col-form-label"> Good Name :</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(m => m.GoodName)
                    </div>
                </div>
                <div class=" form-group row">
                    <label for="colFormLabel" class="col-sm-4 col-form-label"> Image Url :</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(m => m.ImageUrl)
                    </div>
                </div>
                <div class=" form-group row">
                    <label for="colFormLabel" class="col-sm-4 col-form-label"> Short Description :</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(m => m.ShortDescription)
                    </div>
                </div>
                <div class=" form-group row">
                    <label for="colFormLabel" class="col-sm-4 col-form-label"> CategoryId :</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(m => m.CategoryId)
                    </div>
                </div>
                <div class=" form-group row">
                    <label for="colFormLabel" class="col-sm-4 col-form-label"> Price :</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(m => m.Price)
                    </div>
                </div>
                <div class=" form-group row">
                    <label for="colFormLabel" class="col-sm-4 col-form-label"> Good Count :</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(m => m.GoodCount)
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    <a href="@Url.Action("Index", "Admin")" class="text-info link mr-3 p-2">Cancel and return to List</a>
                    <button type="submit" class="btn btn-outline-success">Save</button>
                </div>
            </div>
        </div>

    }
</div>

Shop0.1/Views/Admin/Pagination.cshtml
@model DAL.Good

<div class="d-flex flex-row-reverse bd-highlight">
    <div class="p-2 bd-highlight">
        <nav>
            <ul class="pagination">
                @for (int i = 0; i < ViewBag.CountOfPages; i++)
                {
                    <li class="page-item">
                        @Html.ActionLink((i + 1).ToString(), "Index", new { id = i + 1 }, new { @class = "page-link" })
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>

Shop0.1/Views/Cart/Checkout.cshtml
@model DAL.Entities.ShippingDetails
@{
    ViewBag.Title = "Checkout";
}

<div class="container">
    <div class="row justify-content-center" style="margin-top:50px;margin-bottom:50px;">
        <h2>Check out now</h2>
    </div>
        @Html.ValidationSummary()
       <h6> Please enter your details, and we'll ship your goods right away!</h6><br/>
        @using (Html.BeginForm())
        {
            <h5>Ship to</h5>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Name:</label>
                <div class="col-sm-10">
                    <input class="form-control" placeholder="Name" name="Name" required>
                </div>
            </div>
            <h5>Address</h5>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Line 1:</label>
                <div class="col-sm-10">
                    <input class="form-control" placeholder="Line 1" name="Line1" required>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Line 2:</label>
                <div class="col-sm-10">
                    <input class="form-control" placeholder="Line 2" name="Line2" required>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Line 3:</label>
                <div class="col-sm-10">
                    <input class="form-control" placeholder="Line 3" name="Line3" required>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">City:</label>
                <div class="col-sm-10">
                    <input class="form-control" placeholder="City" name="City" required>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">State:</label>
                <div class="col-sm-10">
                    <input class="form-control" placeholder="State" name="State" required>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Zip:</label>
                <div class="col-sm-10">
                    <input class="form-control" placeholder="Zip" name="Zip" required>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Country:</label>
                <div class="col-sm-10">
                    <input class="form-control" placeholder="Country" name="Country" required>
                </div>
            </div>
            <h5>Options</h5>
            <label>
                @Html.EditorFor(x => x.GiftWrap)
                Gift wrap these items
            </label>

            <p align="center">
                <input class="btn actionButtons btn-success" type="submit" value="Complete order" />
            </p>
        }
    </div>

Shop0.1/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Order Submitted";
}


<div class="row justify-content-center" style="margin-top:50px;">
    <h2>Thanks!</h2>
</div>
<div class="row justify-content-center">
    <p class="font-weight-lighter">Thanks for placing your order. We'll ship your goods as soon as possible.</p>
</div>

Shop0.1/Views/Cart/Index.cshtml
@model Shop0._1.Models.CartIndexViewModel
@{
    ViewBag.Title = "Cart";
}
    <div class="row justify-content-center" style="margin-top:50px;margin-bottom:50px;">
        <h2>Your basket</h2>
    </div>
<div class="row">
    <table class="table table-hover">
        <thead>
            <tr>

                <th scope="col">Quantity</th>
                <th scope="col">Item</th>
                <th scope="col">Short description</th>
                <th scope="col">Price</th>
                <th scope="col">Subtotal</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.Cart.Lines)
            {
            <tr>
                <td>@line.Quantity</td>
                <td>@line.Good.GoodName</td>
                <td>@line.Good.ShortDescription</td>
                <td>@line.Good.Price.ToString("c")</td>
                <td>@((line.Quantity * line.Good.Price).ToString("c"))</td>
                <td>
                    <button id="btnitems" type="button" class="btn btn-danger">
                        @Html.ActionLink("Remove", "RemoveFromCart", "Cart", new { goodId = line.Good.GoodId, returnUrl = Request.Url.PathAndQuery }, null)
                    </button>
                </td>
            </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" align="right"><h5>Total:</h5></td>
                <td>
                    @Model.Cart.ComputeTotalValue().ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>
</div>
    <div class="row d-flex justify-content-center">
        <a href="@Model.ReturnUrl"  class="btn btn-info btn-lg m-1" role="button" aria-pressed="true">Continue shopping</a>
        <a href="@Url.Action("Checkout")" class="btn btn-success btn-lg m-1" role="button" aria-pressed="true">Checkout now</a>
    </div>

Shop0.1/Views/Cart/Summary.cshtml
@model DAL.Entities.Cart

<div id="cart">
    
    @*<span class="caption">
        <b>Your cart:</b>
        @Model.Lines.Sum(x => x.Quantity) item(s),               // item's count and total value/price
        @Model.ComputeTotalValue().ToString("c")
    </span>*@
    <a class="btn btn-success" href="@Url.Action("Index", "Cart",new { returnUrl = Request.Url.PathAndQuery })">Checkout <span class="badge badge-light">@Model.Lines.Sum(x => x.Quantity)</span></a>
    
    
    
    @*@Html.ActionLink("Checkout", "Index", "Cart",
                    new { returnUrl = Request.Url.PathAndQuery },
                    new { @class = "btn btn-outline-success" })*@
</div>

Shop0.1/Views/Good/AllGood.cshtml
@model DAL.Good
@{
    ViewBag.Title = "Canon";

}

<div class="row justify-content-center" style="margin-top:50px;margin-bottom:50px;">
    <h2>All product</h2>
</div>

<div class="row">
    @foreach (var good in ViewBag.Goods)
    {
        <div class="col-md-4" style="margin: 5px 0px;padding: 2px 5px;">
            <div class="card">
                <img src="@Url.Content("~/" + good.ImageUrl + ".jpg")" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@good.GoodName</h5>
                    <p class="card-text">@good.ShortDescription</p>
                    <h5 class="card-text"> @good.Price.ToString("c")</h5>
                    <a id="btnitems" class="btn btn-info" href="@Url.Action("AddToCart", "Cart",new
                                                                            {
                                                                                goodId = good.GoodId,
                                                                                returnUrl = Request.Url.PathAndQuery
                                                                            })">Add to basket</a>
                </div>
            </div>
        </div>
    }
</div>

<div class="d-flex flex-row-reverse bd-highlight">
    <div class="p-2 bd-highlight">
        <nav>
            <ul class="pagination">
                  @for (int i = 0; i < ViewBag.CountOfPages; i++)
                  {
                      <li class="page-item">
                          @Html.ActionLink((i + 1).ToString(), "AllGood", new { id = i + 1 }, new { @class = "page-link" })
                      </li>
                  }
            </ul>
        </nav>
    </div>
</div>

Shop0.1/Views/Good/Camcoders.cshtml
@model DAL.Good

@{
    ViewBag.Title = "Camcoders";
}

<div class="row justify-content-center" style="margin-top:50px;margin-bottom:50px;">
    <h2>Camcoders</h2>
</div>
<div class="row">
    @foreach (var good in ViewBag.Goods)
    {
        <div class="col-md-4" style="margin: 5px 0px;padding: 2px 5px;">
            <div class="card">
                <img src="@Url.Content("~/" + good.ImageUrl + ".jpg")" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@good.GoodName</h5>
                    <p class="card-text">@good.ShortDescription</p>
                    <h5 class="card-text"> @good.Price.ToString("c")</h5>
                    <a id="btnitems" class="btn btn-info" href="@Url.Action("AddToCart", "Cart",new
                                                                            {
                                                                                goodId = good.GoodId,
                                                                                returnUrl = Request.Url.PathAndQuery
                                                                            })">Add to basket</a>
                </div>
            </div>
        </div>
    }
</div>

Shop0.1/Views/Good/Cameras.cshtml
@model DAL.Good

@{
    ViewBag.Title = "Cameras";
}
<div class="row justify-content-center" style="margin-top:50px;margin-bottom:50px;">
    <h2>Cameras</h2>
</div>
<div class="row">
    @foreach (var good in ViewBag.Goods)
    {
        <div class="col-md-4" style="margin: 5px 0px;padding: 2px 5px;">
            <div class="card">
                <img src="@Url.Content("~/" + good.ImageUrl + ".jpg")" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@good.GoodName</h5>
                    <p class="card-text">@good.ShortDescription</p>
                    <h5 class="card-text"> @good.Price.ToString("c")</h5>
                    <a id="btnitems" class="btn btn-info" href="@Url.Action("AddToCart", "Cart",new
                                                                            {
                                                                                goodId = good.GoodId,
                                                                                returnUrl = Request.Url.PathAndQuery
                                                                            })">Add to basket</a>
                </div>
            </div>
        </div>
    }
</div>

Shop0.1/Views/Good/Index.cshtml
@model DAL.Good
@{
    ViewBag.Title = "Canon";

}


<div class="container">
    <div class="row" >
        @foreach (var good in ViewBag.Goods)
        {
            <div class="col-md-4" >
                <div class="card">
                    <img src="@Url.Content("~/" + good.ImageUrl + ".jpg")" class="card-img-top"  alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@good.GoodName</h5>
                        <p class="card-text">@good.ShortDescription</p>
                        <h3 class="card-text"> @good.Price</h3>
                        <button type="button" class="btn btn-success">Buy</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<nav>
    <ul class="pagination">
        @for (int i = 0; i < ViewBag.CountOfPages; i++)
        {
            <li class="page-item">
                @Html.ActionLink((i + 1).ToString(), "Index", new { id = i + 1 }, new { @class = "page-link" })
            </li>
        }
    </ul>
</nav>

Shop0.1/Views/Good/Lenses.cshtml
@model DAL.Good

@{
    ViewBag.Title = "Lenses";
}

<div class="row justify-content-center" style="margin-top:50px;margin-bottom:50px;">
    <h2>Lenses</h2>
</div>
<div class="row">
    @foreach (var good in ViewBag.Goods)
    {
        <div class="col-md-4" style="margin: 5px 0px;padding: 2px 5px;">
            <div class="card">
                <img src="@Url.Content("~/" + good.ImageUrl + ".jpg")" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@good.GoodName</h5>
                    <p class="card-text">@good.ShortDescription</p>
                    <h5 class="card-text"> @good.Price.ToString("c")</h5>
                    <a id="btnitems" class="btn btn-info" href="@Url.Action("AddToCart", "Cart",new
                                                                            {
                                                                                goodId = good.GoodId,
                                                                                returnUrl = Request.Url.PathAndQuery
                                                                            })">Add to basket</a>
                </div>
            </div>
        </div>
    }
</div>

Shop0.1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="/pict/icon.png" type="image/x-icon">
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" media="screen" runat="server" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar  navbar-expand-lg navbar-light bg-light">
        <div class="logoimage"><img src="~/pict/logo.png" width="150"></div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("AllGood", "Good")">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Cameras", "Good")">CAMERAS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Lenses", "Good")">LENSES</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Camcoders", "Good" )">CAMCODERS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Admin")">ADMIN</a>
                </li>
            </ul>
            <div class="btn-group">
                <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="icon" src="~/pict/regicon.png" />
                </button>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
                    <p class="dropdown">Welcome to the Canon <br />Store</p>
                    <div class="dropdown-divider"></div>
                    <button id="btnreg" type="button" class="btn btn-primary btn-lg rounded-pill float-center">SIGN IN / REGISTER</button>
                </div>
            </div>
            <div class="my-2 my-sm-0">
                @{Html.RenderAction("Summary", "Cart");}
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Created by Yana Lytvynchyk</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>